### ISSUE TITLE
Proxy entities should be removed for deleted pods

### ISSUE THREAD

**Issue by maxwangvmt** [turbonomic/prometurbo#16]
Prometurbo will created proxy entities for those deleted pods as Prometheus server will still have the metrics available. Prometurbo currently has no way to figure out if pods are deleted. 

At server side, the proxy entities of the deleted pods will not be stitched with kubeturbo. It's not desired to show them in UI. So, need to investigate how to remove the proxy entities in SDK framework if they are not stitched at server side.

**Comment by chlam4** [comment]
SDK on the server side provides a way for that already, but perhaps we need to add that support in go-sdk.  In Java, this is the API:  EntityBuilder.proxy(boolean keepStandalone).  If keepStandalone is false, then the proxy entity will be deleted if not stitched.

**Comment by maxwangvmt** [comment]
This issue has been fixed by setting keepStandalone false as @chlam4 pointed out.
