### ISSUE TITLE
Prometurbo Operator's CRD requires update to apiextensions version to support k8s 1.22+

### ISSUE THREAD

**Issue by evat-pm** [turbonomic/prometurbo#69]
The CRD for the operator uses apiVersion: apiextensions.k8s.io/v1beta1 and this is officially deprecated in k8s 1.22
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122.

This will cause this CRD are related operator to not deploy into any kubernetes cluster v1.22 or higher.

Need to update the apiextensions to v1 and update related schema, validations.

**Comment by esara** [comment]
the prometurbo crd was updated to v1
https://github.com/turbonomic/prometurbo/blob/master/deploy/prometurbo-operator/config/crd/bases/charts.helm.k8s.io_prometurboes.yaml
and the prometurbo certified operator (8.5.0) was published for all OCP versions (include 4.9 and 4.10)
https://catalog.redhat.com/software/operators/detail/5e98734fd4ae96b7493f08e8
